Fixed RSpec helper by requiring Active Support delegation
Necessary to resolve these errors in the test suite:

[source,ruby]
----
NoMethodError:
  undefined method 'delegate_missing_to' for class Rails::Initializable::Collection
----

This link:https://youtrack.jetbrains.com/projects/RUBY/issues/RUBY-34689/Cannot-run-Rails-console-with-Rails-8.1.0.beta1[discussion] was helpful in tracking this problem down but unclear what changed in Rails to have this crop up.

Issue: 176
Milestone: patch